# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        apikey_provider:
            id: app.security.apikey_provider
        in_memory:
            memory: ~
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/api-login
            stateless: true
            simple_preauth:
                authenticator: app.security.apikey_authenticator
            provider: apikey_provider

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
            - { path: ^/api, roles: ROLE_API }

    encoders:
        AppBundle\Entity\ClientUser:
            algorithm: bcrypt
            cost: 12